// AUTO-GENERATED from the SDR Priority List spreadsheet. Do not edit by hand.
import type { SampleAgent, AgentProfileExtras } from '@/types/admin'

export const SDR_APPLICANT_AGENTS: SampleAgent[] = [
  {
    "id": "AD-3005",
    "name": "Soliana Berhanu",
    "role": "Sales Dev Rep",
    "status": "recruit",
    "client": "—",
    "score": 89,
    "certs": 0,
    "years": 1,
    "langs": [
      "EN",
      "AM"
    ],
    "skills": [
      "Outbound",
      "Sales",
      "Communication"
    ],
    "rate": 0
  },
  {
    "id": "AD-3006",
    "name": "Noud Zewgemichael",
    "role": "Sales Dev Rep",
    "status": "recruit",
    "client": "—",
    "score": 91,
    "certs": 0,
    "years": 1,
    "langs": [
      "EN",
      "AM"
    ],
    "skills": [
      "Outbound",
      "Sales",
      "Communication"
    ],
    "rate": 0
  },
  {
    "id": "AD-3007",
    "name": "Anthony Chibuzo Okoye",
    "role": "Sales Dev Rep",
    "status": "recruit",
    "client": "—",
    "score": 93,
    "certs": 0,
    "years": 1,
    "langs": [
      "EN"
    ],
    "skills": [
      "Outbound",
      "Sales",
      "Communication"
    ],
    "rate": 0
  },
  {
    "id": "AD-3008",
    "name": "Addisu",
    "role": "Sales Dev Rep",
    "status": "recruit",
    "client": "—",
    "score": 83,
    "certs": 0,
    "years": 0,
    "langs": [
      "EN",
      "AM"
    ],
    "skills": [
      "Communication",
      "Eager to learn"
    ],
    "rate": 0
  },
  {
    "id": "AD-3009",
    "name": "Aribidesi Oluwakayode Afolabi",
    "role": "Sales Dev Rep",
    "status": "recruit",
    "client": "—",
    "score": 82,
    "certs": 0,
    "years": 1,
    "langs": [
      "EN",
      "AM"
    ],
    "skills": [
      "Outbound",
      "Sales",
      "Communication"
    ],
    "rate": 0
  },
  {
    "id": "AD-3010",
    "name": "Alula Ayalew",
    "role": "Sales Dev Rep",
    "status": "recruit",
    "client": "—",
    "score": 91,
    "certs": 0,
    "years": 1,
    "langs": [
      "EN",
      "AM"
    ],
    "skills": [
      "Outbound",
      "Sales",
      "Communication"
    ],
    "rate": 0
  },
  {
    "id": "AD-3011",
    "name": "AMANUEL SAMSON SEYOUM",
    "role": "Sales Dev Rep",
    "status": "recruit",
    "client": "—",
    "score": 92,
    "certs": 0,
    "years": 1,
    "langs": [
      "EN",
      "AM"
    ],
    "skills": [
      "Outbound",
      "Sales",
      "Communication"
    ],
    "rate": 0
  },
  {
    "id": "AD-3012",
    "name": "Ejue Annabel Gift",
    "role": "Sales Dev Rep",
    "status": "recruit",
    "client": "—",
    "score": 91,
    "certs": 0,
    "years": 1,
    "langs": [
      "EN"
    ],
    "skills": [
      "Outbound",
      "Sales",
      "Communication"
    ],
    "rate": 0
  },
  {
    "id": "AD-3013",
    "name": "Abeselom Teklehaimanot",
    "role": "Sales Dev Rep",
    "status": "recruit",
    "client": "—",
    "score": 87,
    "certs": 0,
    "years": 0,
    "langs": [
      "EN",
      "AM"
    ],
    "skills": [
      "Communication",
      "Eager to learn"
    ],
    "rate": 0
  },
  {
    "id": "AD-3014",
    "name": "Amarachi Orji",
    "role": "Sales Dev Rep",
    "status": "recruit",
    "client": "—",
    "score": 90,
    "certs": 0,
    "years": 1,
    "langs": [
      "EN"
    ],
    "skills": [
      "Outbound",
      "Sales",
      "Communication"
    ],
    "rate": 0
  },
  {
    "id": "AD-3015",
    "name": "Bilen Hailu Moges",
    "role": "Sales Dev Rep",
    "status": "recruit",
    "client": "—",
    "score": 82,
    "certs": 0,
    "years": 1,
    "langs": [
      "EN",
      "AM"
    ],
    "skills": [
      "Outbound",
      "Sales",
      "Communication"
    ],
    "rate": 0
  },
  {
    "id": "AD-3016",
    "name": "Sosin Zerihun",
    "role": "Sales Dev Rep",
    "status": "recruit",
    "client": "—",
    "score": 86,
    "certs": 0,
    "years": 1,
    "langs": [
      "EN",
      "AM"
    ],
    "skills": [
      "Outbound",
      "Sales",
      "Communication"
    ],
    "rate": 0
  },
  {
    "id": "AD-3017",
    "name": "Kidist Solomon",
    "role": "Sales Dev Rep",
    "status": "recruit",
    "client": "—",
    "score": 89,
    "certs": 0,
    "years": 1,
    "langs": [
      "EN",
      "AM"
    ],
    "skills": [
      "Outbound",
      "Sales",
      "Communication"
    ],
    "rate": 0
  },
  {
    "id": "AD-3018",
    "name": "Biruktawit Adane Ewnetu",
    "role": "Sales Dev Rep",
    "status": "recruit",
    "client": "—",
    "score": 90,
    "certs": 0,
    "years": 1,
    "langs": [
      "EN",
      "AM"
    ],
    "skills": [
      "Outbound",
      "Sales",
      "Communication"
    ],
    "rate": 0
  },
  {
    "id": "AD-3019",
    "name": "Tsinat Mengesha",
    "role": "Sales Dev Rep",
    "status": "recruit",
    "client": "—",
    "score": 89,
    "certs": 0,
    "years": 1,
    "langs": [
      "EN"
    ],
    "skills": [
      "Outbound",
      "Sales",
      "Communication"
    ],
    "rate": 0
  },
  {
    "id": "AD-3020",
    "name": "ABEL DEREJE MEKONNEN",
    "role": "Sales Dev Rep",
    "status": "recruit",
    "client": "—",
    "score": 93,
    "certs": 0,
    "years": 1,
    "langs": [
      "EN",
      "AM"
    ],
    "skills": [
      "Outbound",
      "Sales",
      "Communication"
    ],
    "rate": 0
  },
  {
    "id": "AD-3021",
    "name": "Yeabsira Ayalew",
    "role": "Sales Dev Rep",
    "status": "recruit",
    "client": "—",
    "score": 87,
    "certs": 0,
    "years": 1,
    "langs": [
      "EN",
      "AM"
    ],
    "skills": [
      "Outbound",
      "Sales",
      "Communication"
    ],
    "rate": 0
  },
  {
    "id": "AD-3022",
    "name": "Charity Silla",
    "role": "Sales Dev Rep",
    "status": "recruit",
    "client": "—",
    "score": 86,
    "certs": 0,
    "years": 1,
    "langs": [
      "EN"
    ],
    "skills": [
      "Outbound",
      "Sales",
      "Communication"
    ],
    "rate": 0
  },
  {
    "id": "AD-3023",
    "name": "Ruhama Kinfachew Demeke",
    "role": "Sales Dev Rep",
    "status": "recruit",
    "client": "—",
    "score": 89,
    "certs": 0,
    "years": 1,
    "langs": [
      "EN",
      "AM"
    ],
    "skills": [
      "Outbound",
      "Sales",
      "Communication"
    ],
    "rate": 0
  },
  {
    "id": "AD-3024",
    "name": "Filimon Fekadu Kemaw",
    "role": "Sales Dev Rep",
    "status": "recruit",
    "client": "—",
    "score": 90,
    "certs": 0,
    "years": 1,
    "langs": [
      "EN",
      "AM"
    ],
    "skills": [
      "Outbound",
      "Sales",
      "Communication"
    ],
    "rate": 0
  },
  {
    "id": "AD-3025",
    "name": "Basleal Abera Hiruy",
    "role": "Sales Dev Rep",
    "status": "recruit",
    "client": "—",
    "score": 89,
    "certs": 0,
    "years": 1,
    "langs": [
      "EN",
      "AM"
    ],
    "skills": [
      "Outbound",
      "Sales",
      "Communication"
    ],
    "rate": 0
  },
  {
    "id": "AD-3026",
    "name": "Maereg Hailu Kifle",
    "role": "Sales Dev Rep",
    "status": "recruit",
    "client": "—",
    "score": 87,
    "certs": 0,
    "years": 1,
    "langs": [
      "EN",
      "AM"
    ],
    "skills": [
      "Outbound",
      "Sales",
      "Communication"
    ],
    "rate": 0
  },
  {
    "id": "AD-3027",
    "name": "Mihret Mulatu Tafese",
    "role": "Sales Dev Rep",
    "status": "recruit",
    "client": "—",
    "score": 93,
    "certs": 0,
    "years": 1,
    "langs": [
      "EN",
      "AM"
    ],
    "skills": [
      "Outbound",
      "Sales",
      "Communication"
    ],
    "rate": 0
  },
  {
    "id": "AD-3028",
    "name": "Tensae Girma",
    "role": "Sales Dev Rep",
    "status": "recruit",
    "client": "—",
    "score": 89,
    "certs": 0,
    "years": 1,
    "langs": [
      "EN"
    ],
    "skills": [
      "Outbound",
      "Sales",
      "Communication"
    ],
    "rate": 0
  },
  {
    "id": "AD-3029",
    "name": "Ruth Masresha Bekele",
    "role": "Sales Dev Rep",
    "status": "recruit",
    "client": "—",
    "score": 90,
    "certs": 0,
    "years": 1,
    "langs": [
      "EN",
      "AM"
    ],
    "skills": [
      "Outbound",
      "Sales",
      "Communication"
    ],
    "rate": 0
  },
  {
    "id": "AD-3030",
    "name": "Rediet Dawit Tesema",
    "role": "Sales Dev Rep",
    "status": "recruit",
    "client": "—",
    "score": 83,
    "certs": 0,
    "years": 1,
    "langs": [
      "EN",
      "AM"
    ],
    "skills": [
      "Outbound",
      "Sales",
      "Communication"
    ],
    "rate": 0
  },
  {
    "id": "AD-3031",
    "name": "Mahidere Dawit",
    "role": "Sales Dev Rep",
    "status": "recruit",
    "client": "—",
    "score": 84,
    "certs": 0,
    "years": 1,
    "langs": [
      "EN",
      "AM"
    ],
    "skills": [
      "Outbound",
      "Sales",
      "Communication"
    ],
    "rate": 0
  },
  {
    "id": "AD-3032",
    "name": "kidist shewangizaw",
    "role": "Sales Dev Rep",
    "status": "recruit",
    "client": "—",
    "score": 80,
    "certs": 0,
    "years": 0,
    "langs": [
      "EN",
      "AM"
    ],
    "skills": [
      "Communication",
      "Eager to learn"
    ],
    "rate": 0
  },
  {
    "id": "AD-3033",
    "name": "Metsnanat Tigistu Nidane",
    "role": "Sales Dev Rep",
    "status": "recruit",
    "client": "—",
    "score": 93,
    "certs": 0,
    "years": 1,
    "langs": [
      "EN",
      "AM"
    ],
    "skills": [
      "Outbound",
      "Sales",
      "Communication"
    ],
    "rate": 0
  },
  {
    "id": "AD-3034",
    "name": "Nebait Aemro",
    "role": "Sales Dev Rep",
    "status": "recruit",
    "client": "—",
    "score": 93,
    "certs": 0,
    "years": 1,
    "langs": [
      "EN",
      "AM"
    ],
    "skills": [
      "Outbound",
      "Sales",
      "Communication"
    ],
    "rate": 0
  },
  {
    "id": "AD-3035",
    "name": "Natty Negash",
    "role": "Sales Dev Rep",
    "status": "recruit",
    "client": "—",
    "score": 93,
    "certs": 0,
    "years": 1,
    "langs": [
      "EN"
    ],
    "skills": [
      "Outbound",
      "Sales",
      "Communication"
    ],
    "rate": 0
  },
  {
    "id": "AD-3036",
    "name": "Hermella Mulugeta",
    "role": "Sales Dev Rep",
    "status": "recruit",
    "client": "—",
    "score": 86,
    "certs": 0,
    "years": 1,
    "langs": [
      "EN",
      "AM"
    ],
    "skills": [
      "Outbound",
      "Sales",
      "Communication"
    ],
    "rate": 0
  },
  {
    "id": "AD-3037",
    "name": "Abenezer Fekadu Zenebe",
    "role": "Sales Dev Rep",
    "status": "recruit",
    "client": "—",
    "score": 90,
    "certs": 0,
    "years": 1,
    "langs": [
      "EN",
      "AM"
    ],
    "skills": [
      "Outbound",
      "Sales",
      "Communication"
    ],
    "rate": 0
  },
  {
    "id": "AD-3038",
    "name": "Tigest kifle Abera",
    "role": "Sales Dev Rep",
    "status": "recruit",
    "client": "—",
    "score": 75,
    "certs": 0,
    "years": 0,
    "langs": [
      "EN",
      "AM"
    ],
    "skills": [
      "Communication",
      "Eager to learn"
    ],
    "rate": 0
  },
  {
    "id": "AD-3039",
    "name": "Ermias Abadi Aynalem",
    "role": "Sales Dev Rep",
    "status": "recruit",
    "client": "—",
    "score": 92,
    "certs": 0,
    "years": 1,
    "langs": [
      "EN",
      "AM"
    ],
    "skills": [
      "Outbound",
      "Sales",
      "Communication"
    ],
    "rate": 0
  },
  {
    "id": "AD-3040",
    "name": "Amanuel Belete",
    "role": "Sales Dev Rep",
    "status": "recruit",
    "client": "—",
    "score": 93,
    "certs": 0,
    "years": 1,
    "langs": [
      "EN",
      "AM"
    ],
    "skills": [
      "Outbound",
      "Sales",
      "Communication"
    ],
    "rate": 0
  },
  {
    "id": "AD-3041",
    "name": "Rahel Teshome zeleke",
    "role": "Sales Dev Rep",
    "status": "recruit",
    "client": "—",
    "score": 93,
    "certs": 0,
    "years": 1,
    "langs": [
      "EN",
      "AM"
    ],
    "skills": [
      "Outbound",
      "Sales",
      "Communication"
    ],
    "rate": 0
  },
  {
    "id": "AD-3042",
    "name": "Mahlet Tadesse",
    "role": "Sales Dev Rep",
    "status": "recruit",
    "client": "—",
    "score": 87,
    "certs": 0,
    "years": 1,
    "langs": [
      "EN",
      "AM"
    ],
    "skills": [
      "Outbound",
      "Sales",
      "Communication"
    ],
    "rate": 0
  },
  {
    "id": "AD-3043",
    "name": "Kunuz Mohammed Berta",
    "role": "Sales Dev Rep",
    "status": "recruit",
    "client": "—",
    "score": 88,
    "certs": 0,
    "years": 1,
    "langs": [
      "EN",
      "AM"
    ],
    "skills": [
      "Outbound",
      "Sales",
      "Communication"
    ],
    "rate": 0
  },
  {
    "id": "AD-3044",
    "name": "Abel yematawork",
    "role": "Sales Dev Rep",
    "status": "recruit",
    "client": "—",
    "score": 80,
    "certs": 0,
    "years": 0,
    "langs": [
      "EN",
      "AM"
    ],
    "skills": [
      "Communication",
      "Eager to learn"
    ],
    "rate": 0
  },
  {
    "id": "AD-3045",
    "name": "Biruk Abera",
    "role": "Sales Dev Rep",
    "status": "recruit",
    "client": "—",
    "score": 92,
    "certs": 0,
    "years": 1,
    "langs": [
      "EN",
      "AM"
    ],
    "skills": [
      "Outbound",
      "Sales",
      "Communication"
    ],
    "rate": 0
  },
  {
    "id": "AD-3046",
    "name": "Ezana Hailemariam",
    "role": "Sales Dev Rep",
    "status": "recruit",
    "client": "—",
    "score": 91,
    "certs": 0,
    "years": 1,
    "langs": [
      "EN",
      "AM"
    ],
    "skills": [
      "Outbound",
      "Sales",
      "Communication"
    ],
    "rate": 0
  },
  {
    "id": "AD-3047",
    "name": "Amanuel Demeke",
    "role": "Sales Dev Rep",
    "status": "recruit",
    "client": "—",
    "score": 85,
    "certs": 0,
    "years": 0,
    "langs": [
      "EN",
      "AM"
    ],
    "skills": [
      "Communication",
      "Eager to learn"
    ],
    "rate": 0
  },
  {
    "id": "AD-3048",
    "name": "Hermela Asfaw",
    "role": "Sales Dev Rep",
    "status": "recruit",
    "client": "—",
    "score": 78,
    "certs": 0,
    "years": 0,
    "langs": [
      "EN",
      "AM"
    ],
    "skills": [
      "Communication",
      "Eager to learn"
    ],
    "rate": 0
  },
  {
    "id": "AD-3049",
    "name": "Selamawit Teshome",
    "role": "Sales Dev Rep",
    "status": "recruit",
    "client": "—",
    "score": 89,
    "certs": 0,
    "years": 1,
    "langs": [
      "EN",
      "AM"
    ],
    "skills": [
      "Outbound",
      "Sales",
      "Communication"
    ],
    "rate": 0
  },
  {
    "id": "AD-3050",
    "name": "Eden Abay",
    "role": "Sales Dev Rep",
    "status": "recruit",
    "client": "—",
    "score": 89,
    "certs": 0,
    "years": 1,
    "langs": [
      "EN",
      "AM"
    ],
    "skills": [
      "Outbound",
      "Sales",
      "Communication"
    ],
    "rate": 0
  },
  {
    "id": "AD-3051",
    "name": "Gelila Teshome Shenkute",
    "role": "Sales Dev Rep",
    "status": "recruit",
    "client": "—",
    "score": 90,
    "certs": 0,
    "years": 1,
    "langs": [
      "EN",
      "AM"
    ],
    "skills": [
      "Outbound",
      "Sales",
      "Communication"
    ],
    "rate": 0
  },
  {
    "id": "AD-3052",
    "name": "Helina Teshale",
    "role": "Sales Dev Rep",
    "status": "recruit",
    "client": "—",
    "score": 91,
    "certs": 0,
    "years": 1,
    "langs": [
      "EN",
      "AM"
    ],
    "skills": [
      "Outbound",
      "Sales",
      "Communication"
    ],
    "rate": 0
  },
  {
    "id": "AD-3053",
    "name": "Samrawit Yeshitila",
    "role": "Sales Dev Rep",
    "status": "recruit",
    "client": "—",
    "score": 85,
    "certs": 0,
    "years": 0,
    "langs": [
      "EN"
    ],
    "skills": [
      "Communication",
      "Eager to learn"
    ],
    "rate": 0
  },
  {
    "id": "AD-3054",
    "name": "Redwan Ibrahim Nurhussien",
    "role": "Sales Dev Rep",
    "status": "recruit",
    "client": "—",
    "score": 84,
    "certs": 0,
    "years": 0,
    "langs": [
      "EN",
      "AM"
    ],
    "skills": [
      "Communication",
      "Eager to learn"
    ],
    "rate": 0
  }
]

export const SDR_APPLICANT_EXTRAS: Record<string, AgentProfileExtras> = {
  "AD-3005": {
    "headline": "SDR applicant · prior sales experience",
    "pitch": "Applicant for the Sales Development Representative role. Real contact details, intro recording, and intake answers are captured from the application form below.",
    "location": "Addis Ababa, ET",
    "timezone": "EAT (UTC+3)",
    "hours": "Part-time (20–30 hrs/week)",
    "email": "Solianaberhanu87@gmail.com",
    "phone": "+251942588070",
    "employer": "—",
    "contractType": "Part-time (20–30 hrs/week)",
    "payRate": "—",
    "billRate": "—",
    "margin": "—",
    "started": "—",
    "deployedSince": "—",
    "csat": null,
    "aht": null,
    "qa": 0,
    "tools": [],
    "education": "—",
    "certifications": [],
    "history": [],
    "notes": [],
    "vocaroo": "1eftEfyRodmO",
    "intake": {
      "availability": "Part-time (20–30 hrs/week)",
      "experience": "Yes",
      "lateHours": "Yes",
      "device": "8GB RAM, Intel i5, 932GB HDD",
      "phoneModel": "Iphone 12",
      "internet": "64Mbps",
      "cvUrl": "https://drive.google.com/open?id=1L4mU1PGFQ4Ffb7MKND_A0qkiWQmsheE9"
    }
  },
  "AD-3006": {
    "headline": "SDR applicant · prior sales experience",
    "pitch": "Applicant for the Sales Development Representative role. Real contact details, intro recording, and intake answers are captured from the application form below.",
    "location": "Addis Ababa, ET",
    "timezone": "EAT (UTC+3)",
    "hours": "Full-time (40 hrs/week)",
    "email": "zewgenoud@gmail.com",
    "phone": "0931723242",
    "employer": "—",
    "contractType": "Full-time (40 hrs/week)",
    "payRate": "—",
    "billRate": "—",
    "margin": "—",
    "started": "—",
    "deployedSince": "—",
    "csat": null,
    "aht": null,
    "qa": 0,
    "tools": [],
    "education": "—",
    "certifications": [],
    "history": [],
    "notes": [],
    "vocaroo": "1oFVSGjCqukw",
    "intake": {
      "availability": "Full-time (40 hrs/week)",
      "experience": "Yes",
      "lateHours": "Yes",
      "device": "16gb ram, 118 SSD 1 tb HDD intel i5",
      "phoneModel": "Android 13 Samsung s 10+",
      "internet": "20mbs",
      "cvUrl": "https://drive.google.com/open?id=12VM63phKC4OKF1fZwzfQFOypeb9sgMsJ"
    }
  },
  "AD-3007": {
    "headline": "SDR applicant · prior sales experience",
    "pitch": "Applicant for the Sales Development Representative role. Real contact details, intro recording, and intake answers are captured from the application form below.",
    "location": "Germany",
    "timezone": "—",
    "hours": "Full-time (40 hrs/week)",
    "email": "antuabuzo5@gmail.com",
    "phone": "+49 1633691614",
    "employer": "—",
    "contractType": "Full-time (40 hrs/week)",
    "payRate": "—",
    "billRate": "—",
    "margin": "—",
    "started": "—",
    "deployedSince": "—",
    "csat": null,
    "aht": null,
    "qa": 0,
    "tools": [],
    "education": "—",
    "certifications": [],
    "history": [],
    "notes": [],
    "vocaroo": "11Q7VvgrotHZ",
    "intake": {
      "availability": "Full-time (40 hrs/week)",
      "experience": "Yes",
      "lateHours": "Yes",
      "device": "16GB RAM, Intel Core i5-5200U processor, 256GB SSD, Windows 10 Pro (64-bit)",
      "phoneModel": "Samsung Galaxy S22 Ultra, Android 15",
      "internet": "57.15 Mbps download / 42.03 Mbps upload",
      "cvUrl": "https://drive.google.com/open?id=1wtyUjsWcZKBUm9fy9VlR29L3ufl8tbpx"
    }
  },
  "AD-3008": {
    "headline": "SDR applicant",
    "pitch": "Applicant for the Sales Development Representative role. Real contact details, intro recording, and intake answers are captured from the application form below.",
    "location": "Addis Ababa, ET",
    "timezone": "EAT (UTC+3)",
    "hours": "Part-time (20–30 hrs/week)",
    "email": "Teklu",
    "phone": "0952570660",
    "employer": "—",
    "contractType": "Part-time (20–30 hrs/week)",
    "payRate": "—",
    "billRate": "—",
    "margin": "—",
    "started": "—",
    "deployedSince": "—",
    "csat": null,
    "aht": null,
    "qa": 0,
    "tools": [],
    "education": "—",
    "certifications": [],
    "history": [],
    "notes": [],
    "intake": {
      "availability": "Part-time (20–30 hrs/week)",
      "experience": "No experience (but willing to learn)",
      "lateHours": "Yes",
      "device": "Yes",
      "phoneModel": "Yes",
      "internet": "Yes",
      "cvUrl": "https://drive.google.com/open?id=1pHffTfrzma763Hv2IPZpblYoQSapblNqZWrd-naaAlI"
    }
  },
  "AD-3009": {
    "headline": "SDR applicant · prior sales experience",
    "pitch": "Applicant for the Sales Development Representative role. Real contact details, intro recording, and intake answers are captured from the application form below.",
    "location": "Addis Ababa, ET",
    "timezone": "EAT (UTC+3)",
    "hours": "Part-time (20–30 hrs/week)",
    "email": "afolabitechies@gmail.com",
    "phone": "09127914631",
    "employer": "—",
    "contractType": "Part-time (20–30 hrs/week)",
    "payRate": "—",
    "billRate": "—",
    "margin": "—",
    "started": "—",
    "deployedSince": "—",
    "csat": null,
    "aht": null,
    "qa": 0,
    "tools": [],
    "education": "—",
    "certifications": [],
    "history": [],
    "notes": [],
    "intake": {
      "availability": "Part-time (20–30 hrs/week)",
      "experience": "Yes",
      "lateHours": "Yes",
      "device": "4G RAM Redmi 13C",
      "phoneModel": "Android 14",
      "internet": "4G",
      "cvUrl": "https://drive.google.com/open?id=1hp6MA1CiX6rASiBFt0yZQbZouY8-g0KH"
    }
  },
  "AD-3010": {
    "headline": "SDR applicant · prior sales experience",
    "pitch": "Applicant for the Sales Development Representative role. Real contact details, intro recording, and intake answers are captured from the application form below.",
    "location": "Addis Ababa, ET",
    "timezone": "EAT (UTC+3)",
    "hours": "Full-time (40 hrs/week)",
    "email": "alulaayalew45@gmail.com",
    "phone": "+251919372751",
    "employer": "—",
    "contractType": "Full-time (40 hrs/week)",
    "payRate": "—",
    "billRate": "—",
    "margin": "—",
    "started": "—",
    "deployedSince": "—",
    "csat": null,
    "aht": null,
    "qa": 0,
    "tools": [],
    "education": "—",
    "certifications": [],
    "history": [],
    "notes": [],
    "vocaroo": "1c30obSMLEcE",
    "intake": {
      "availability": "Full-time (40 hrs/week)",
      "experience": "Yes",
      "lateHours": "Yes",
      "device": "Core I7, 10th Gen, 16GB RAM, 512 SSD",
      "phoneModel": "Iphone 13",
      "internet": "Download speed - 50Mbps. Upload speed - 53Mbps",
      "cvUrl": "https://drive.google.com/open?id=1IU3VjCdeSGJiTk7Hs_hdWxCWd1VvXKPx"
    }
  },
  "AD-3011": {
    "headline": "SDR applicant · prior sales experience",
    "pitch": "Applicant for the Sales Development Representative role. Real contact details, intro recording, and intake answers are captured from the application form below.",
    "location": "Addis Ababa, ET",
    "timezone": "EAT (UTC+3)",
    "hours": "Full-time (40 hrs/week)",
    "email": "ghostsamdk@gmail.com",
    "phone": "0713156211",
    "employer": "—",
    "contractType": "Full-time (40 hrs/week)",
    "payRate": "—",
    "billRate": "—",
    "margin": "—",
    "started": "—",
    "deployedSince": "—",
    "csat": null,
    "aht": null,
    "qa": 0,
    "tools": [],
    "education": "—",
    "certifications": [],
    "history": [],
    "notes": [],
    "vocaroo": "11pYWYjPWc1I",
    "intake": {
      "availability": "Full-time (40 hrs/week)",
      "experience": "Yes",
      "lateHours": "Yes",
      "device": "16gb ram, Intel core i5(7TH GENERATION),1 TB SSD",
      "phoneModel": "Techno camon 20 pro",
      "internet": "30 mega byte per second (30mb)",
      "cvUrl": "https://drive.google.com/open?id=1guAX5FFoGD2nSDSnGbW_C9r2HF3ZwHIv"
    }
  },
  "AD-3012": {
    "headline": "SDR applicant · prior sales experience",
    "pitch": "Applicant for the Sales Development Representative role. Real contact details, intro recording, and intake answers are captured from the application form below.",
    "location": "Remote",
    "timezone": "—",
    "hours": "Full-time (40 hrs/week)",
    "email": "annabelejue81@gmail.com",
    "phone": "08086951946",
    "employer": "—",
    "contractType": "Full-time (40 hrs/week)",
    "payRate": "—",
    "billRate": "—",
    "margin": "—",
    "started": "—",
    "deployedSince": "—",
    "csat": null,
    "aht": null,
    "qa": 0,
    "tools": [],
    "education": "—",
    "certifications": [],
    "history": [],
    "notes": [],
    "intake": {
      "availability": "Full-time (40 hrs/week)",
      "experience": "Yes",
      "lateHours": "Yes",
      "device": "RAM",
      "phoneModel": "Oppo A17",
      "internet": "It's very fast",
      "cvUrl": "https://drive.google.com/open?id=1CPKtoylv9ga8ef7ss-vq4Mxu3wABCSId"
    }
  },
  "AD-3013": {
    "headline": "SDR applicant",
    "pitch": "Applicant for the Sales Development Representative role. Real contact details, intro recording, and intake answers are captured from the application form below.",
    "location": "Addis Ababa, ET",
    "timezone": "EAT (UTC+3)",
    "hours": "Full-time (40 hrs/week)",
    "email": "abeselomteklehaimanot2@gmail.com",
    "phone": "0985413158",
    "employer": "—",
    "contractType": "Full-time (40 hrs/week)",
    "payRate": "—",
    "billRate": "—",
    "margin": "—",
    "started": "—",
    "deployedSince": "—",
    "csat": null,
    "aht": null,
    "qa": 0,
    "tools": [],
    "education": "—",
    "certifications": [],
    "history": [],
    "notes": [],
    "vocaroo": "158VUxrARkM0",
    "intake": {
      "availability": "Full-time (40 hrs/week)",
      "experience": "No experience (but willing to learn)",
      "lateHours": "Yes",
      "device": "16GB RAM, AMD Radeon (TM) Vega 3 Graphics (241 MB), 477 GB SSD",
      "phoneModel": "iPhone XS Max",
      "internet": "Upload-18 Mbps  Download-20Mbps",
      "cvUrl": "https://drive.google.com/open?id=1iXQaODZSkeaAyKeMGmpJ8VeI24ueh3WS"
    }
  },
  "AD-3014": {
    "headline": "SDR applicant · prior sales experience",
    "pitch": "Applicant for the Sales Development Representative role. Real contact details, intro recording, and intake answers are captured from the application form below.",
    "location": "Nigeria",
    "timezone": "—",
    "hours": "Flexible/Project-based",
    "email": "orjiamarachi42@gmail.com",
    "phone": "+2347062942205",
    "employer": "—",
    "contractType": "Flexible/Project-based",
    "payRate": "—",
    "billRate": "—",
    "margin": "—",
    "started": "—",
    "deployedSince": "—",
    "csat": null,
    "aht": null,
    "qa": 0,
    "tools": [],
    "education": "—",
    "certifications": [],
    "history": [],
    "notes": [],
    "introUrl": "https://www.loom.com/share/1bae4525cc4b4eff8e8fa28f795c70bf?sid=9ba66c8a-b7b5-470f-a3f8-750d7b295a4b",
    "intake": {
      "availability": "Flexible/Project-based",
      "experience": "Yes",
      "lateHours": "Yes",
      "device": "16GB RAM Inteli5, 512GB SSD",
      "phoneModel": "Android 13",
      "internet": "My average internet speed is 25 Mbps download / 10 Mbps upload, which supports smooth video calls and online communication.",
      "cvUrl": "https://drive.google.com/open?id=1iSXSagNnARPQ3e27djutmEUrTYoEJT7s"
    }
  },
  "AD-3015": {
    "headline": "SDR applicant · prior sales experience",
    "pitch": "Applicant for the Sales Development Representative role. Real contact details, intro recording, and intake answers are captured from the application form below.",
    "location": "Addis Ababa, ET",
    "timezone": "EAT (UTC+3)",
    "hours": "Part-time (20–30 hrs/week)",
    "email": "bilenhailu21@gmail.com",
    "phone": "+251966690262",
    "employer": "—",
    "contractType": "Part-time (20–30 hrs/week)",
    "payRate": "—",
    "billRate": "—",
    "margin": "—",
    "started": "—",
    "deployedSince": "—",
    "csat": null,
    "aht": null,
    "qa": 0,
    "tools": [],
    "education": "—",
    "certifications": [],
    "history": [],
    "notes": [],
    "vocaroo": "155kKitQOXEa",
    "intake": {
      "availability": "Part-time (20–30 hrs/week)",
      "experience": "Yes",
      "lateHours": "Yes",
      "device": "16GB RAM, lntel 15,",
      "phoneModel": "Android , ZTE blade 2024",
      "internet": "10mbs",
      "cvUrl": "https://drive.google.com/open?id=11O5BDyW42K3HcnsPW21-Mv_CQAxsW72d"
    }
  },
  "AD-3016": {
    "headline": "SDR applicant · prior sales experience",
    "pitch": "Applicant for the Sales Development Representative role. Real contact details, intro recording, and intake answers are captured from the application form below.",
    "location": "Addis Ababa, ET",
    "timezone": "EAT (UTC+3)",
    "hours": "Full-time (40 hrs/week)",
    "email": "sosinazerihun62@gmail.com",
    "phone": "+251945602673",
    "employer": "—",
    "contractType": "Full-time (40 hrs/week)",
    "payRate": "—",
    "billRate": "—",
    "margin": "—",
    "started": "—",
    "deployedSince": "—",
    "csat": null,
    "aht": null,
    "qa": 0,
    "tools": [],
    "education": "—",
    "certifications": [],
    "history": [],
    "notes": [],
    "vocaroo": "1mMlKtab1BsT",
    "intake": {
      "availability": "Full-time (40 hrs/week)",
      "experience": "Yes",
      "lateHours": "Yes",
      "device": "16GB RAM, Intel i3, 512GB",
      "phoneModel": "Infinix Hot 50, Android 14",
      "internet": "25Mbps",
      "cvUrl": "https://drive.google.com/open?id=1URpYbtWmyKo1yPZaDa6MJiPHKNP-YUnE"
    }
  },
  "AD-3017": {
    "headline": "SDR applicant · prior sales experience",
    "pitch": "Applicant for the Sales Development Representative role. Real contact details, intro recording, and intake answers are captured from the application form below.",
    "location": "Addis Ababa, ET",
    "timezone": "EAT (UTC+3)",
    "hours": "Full-time (40 hrs/week)",
    "email": "Kidist1131@gmail.com",
    "phone": "0966714439",
    "employer": "—",
    "contractType": "Full-time (40 hrs/week)",
    "payRate": "—",
    "billRate": "—",
    "margin": "—",
    "started": "—",
    "deployedSince": "—",
    "csat": null,
    "aht": null,
    "qa": 0,
    "tools": [],
    "education": "—",
    "certifications": [],
    "history": [],
    "notes": [],
    "vocaroo": "1hC23Jpi2TUw",
    "intake": {
      "availability": "Full-time (40 hrs/week)",
      "experience": "Yes",
      "lateHours": "Yes",
      "device": "16GB RAM, Intel i7, 512 GB SSD",
      "phoneModel": "Iphone 11 Pro Max",
      "internet": "80.0",
      "cvUrl": "https://drive.google.com/open?id=1CZadTwJrJURWaYL6CpEor0QVYtBgYbhD"
    }
  },
  "AD-3018": {
    "headline": "SDR applicant · prior sales experience",
    "pitch": "Applicant for the Sales Development Representative role. Real contact details, intro recording, and intake answers are captured from the application form below.",
    "location": "Addis Ababa, ET",
    "timezone": "EAT (UTC+3)",
    "hours": "Full-time (40 hrs/week)",
    "email": "biruktihp@gmail.com",
    "phone": "+251924491540",
    "employer": "—",
    "contractType": "Full-time (40 hrs/week)",
    "payRate": "—",
    "billRate": "—",
    "margin": "—",
    "started": "—",
    "deployedSince": "—",
    "csat": null,
    "aht": null,
    "qa": 0,
    "tools": [],
    "education": "—",
    "certifications": [],
    "history": [],
    "notes": [],
    "vocaroo": "1dMuJrfuDWun",
    "intake": {
      "availability": "Full-time (40 hrs/week)",
      "experience": "Yes",
      "lateHours": "Yes",
      "device": "16GB RAM Intel i7 1TB",
      "phoneModel": "Android 13",
      "internet": "70mbs",
      "cvUrl": "https://drive.google.com/open?id=1VoNZqLJWX2nIN51AKrZfwZf4gDPpptol"
    }
  },
  "AD-3019": {
    "headline": "SDR applicant · prior sales experience",
    "pitch": "Applicant for the Sales Development Representative role. Real contact details, intro recording, and intake answers are captured from the application form below.",
    "location": "Remote",
    "timezone": "—",
    "hours": "Full-time (40 hrs/week)",
    "email": "amarechmekuriya9@gmail.com",
    "phone": "2.51955048602E11",
    "employer": "—",
    "contractType": "Full-time (40 hrs/week)",
    "payRate": "—",
    "billRate": "—",
    "margin": "—",
    "started": "—",
    "deployedSince": "—",
    "csat": null,
    "aht": null,
    "qa": 0,
    "tools": [],
    "education": "—",
    "certifications": [],
    "history": [],
    "notes": [],
    "vocaroo": "19N2zigZVBvS",
    "intake": {
      "availability": "Full-time (40 hrs/week)",
      "experience": "Yes",
      "lateHours": "Yes",
      "device": "4GB RAM, Core i5,256GB SSD",
      "phoneModel": "Iphone 11",
      "internet": "5mps",
      "cvUrl": "https://drive.google.com/open?id=1vhdvTcXUPo5LXVUuOp_bfuBbVN_OHrxp"
    }
  },
  "AD-3020": {
    "headline": "SDR applicant · prior sales experience",
    "pitch": "Applicant for the Sales Development Representative role. Real contact details, intro recording, and intake answers are captured from the application form below.",
    "location": "Addis Ababa, ET",
    "timezone": "EAT (UTC+3)",
    "hours": "Full-time (40 hrs/week)",
    "email": "Abel.mekonenn.1@gmail.com",
    "phone": "+251943046339",
    "employer": "—",
    "contractType": "Full-time (40 hrs/week)",
    "payRate": "—",
    "billRate": "—",
    "margin": "—",
    "started": "—",
    "deployedSince": "—",
    "csat": null,
    "aht": null,
    "qa": 0,
    "tools": [],
    "education": "—",
    "certifications": [],
    "history": [],
    "notes": [],
    "vocaroo": "1clELMIYXuIm",
    "intake": {
      "availability": "Full-time (40 hrs/week)",
      "experience": "Yes",
      "lateHours": "Yes",
      "device": "Intel corei7 11thgen 8GB RAM DDR4 PC4 ssd512 nvme",
      "phoneModel": "iPhone 12 promax",
      "internet": "2mb",
      "cvUrl": "https://drive.google.com/open?id=12iLLyqNAr2i2jywjS9ZXvG25CnluSWxU"
    }
  },
  "AD-3021": {
    "headline": "SDR applicant · prior sales experience",
    "pitch": "Applicant for the Sales Development Representative role. Real contact details, intro recording, and intake answers are captured from the application form below.",
    "location": "Addis Ababa, ET",
    "timezone": "EAT (UTC+3)",
    "hours": "Full-time (40 hrs/week)",
    "email": "yeabsiraayalew1@gmail.com",
    "phone": "0932453500",
    "employer": "—",
    "contractType": "Full-time (40 hrs/week)",
    "payRate": "—",
    "billRate": "—",
    "margin": "—",
    "started": "—",
    "deployedSince": "—",
    "csat": null,
    "aht": null,
    "qa": 0,
    "tools": [],
    "education": "—",
    "certifications": [],
    "history": [],
    "notes": [],
    "introUrl": "https://drive.google.com/file/d/1tn81r19lzlj_jok-JJ0RAZJ2orA0FgJk/view?usp=drivesdk",
    "intake": {
      "availability": "Full-time (40 hrs/week)",
      "experience": "Yes",
      "lateHours": "Yes",
      "device": "8GB RAM, Intel(R) i5, 932 HHD",
      "phoneModel": "Iphone 12",
      "internet": "45.59 Mbps",
      "cvUrl": "https://drive.google.com/open?id=18AAPxkGJbPEjzk1fqrOtSEUDv3EdE5cj"
    }
  },
  "AD-3022": {
    "headline": "SDR applicant · prior sales experience",
    "pitch": "Applicant for the Sales Development Representative role. Real contact details, intro recording, and intake answers are captured from the application form below.",
    "location": "Kenya",
    "timezone": "—",
    "hours": "Full-time (40 hrs/week)",
    "email": "charity.silla@gmail.com",
    "phone": "+254728209455",
    "employer": "—",
    "contractType": "Full-time (40 hrs/week)",
    "payRate": "—",
    "billRate": "—",
    "margin": "—",
    "started": "—",
    "deployedSince": "—",
    "csat": null,
    "aht": null,
    "qa": 0,
    "tools": [],
    "education": "—",
    "certifications": [],
    "history": [],
    "notes": [],
    "vocaroo": "1dSq1Pxu52W5",
    "intake": {
      "availability": "Full-time (40 hrs/week)",
      "experience": "Yes",
      "lateHours": "Yes",
      "device": "8GB",
      "phoneModel": "Android 13",
      "internet": "20MBps",
      "cvUrl": "https://drive.google.com/open?id=1H4Qtct18FCmh63REtOxvMDqgyWYe-qsA"
    }
  },
  "AD-3023": {
    "headline": "SDR applicant · prior sales experience",
    "pitch": "Applicant for the Sales Development Representative role. Real contact details, intro recording, and intake answers are captured from the application form below.",
    "location": "Addis Ababa, ET",
    "timezone": "EAT (UTC+3)",
    "hours": "Full-time (40 hrs/week)",
    "email": "ruhama.demeke@gmail.com",
    "phone": "+251929238880",
    "employer": "—",
    "contractType": "Full-time (40 hrs/week)",
    "payRate": "—",
    "billRate": "—",
    "margin": "—",
    "started": "—",
    "deployedSince": "—",
    "csat": null,
    "aht": null,
    "qa": 0,
    "tools": [],
    "education": "—",
    "certifications": [],
    "history": [],
    "notes": [],
    "vocaroo": "1ofiavxqetZY",
    "intake": {
      "availability": "Full-time (40 hrs/week)",
      "experience": "Yes",
      "lateHours": "Yes",
      "device": "Macbook pro m2 chip 2 512GB SSD",
      "phoneModel": "IPhone 12 pro max",
      "internet": "30mbps",
      "cvUrl": "https://drive.google.com/open?id=1ZPwcXK_pEBCtKqXmNXQOrPu8EiRfNzXg"
    }
  },
  "AD-3024": {
    "headline": "SDR applicant · prior sales experience",
    "pitch": "Applicant for the Sales Development Representative role. Real contact details, intro recording, and intake answers are captured from the application form below.",
    "location": "Addis Ababa, ET",
    "timezone": "EAT (UTC+3)",
    "hours": "Full-time (40 hrs/week)",
    "email": "filimonfekadu@gmail.com",
    "phone": "0715022178 or 0949009091",
    "employer": "—",
    "contractType": "Full-time (40 hrs/week)",
    "payRate": "—",
    "billRate": "—",
    "margin": "—",
    "started": "—",
    "deployedSince": "—",
    "csat": null,
    "aht": null,
    "qa": 0,
    "tools": [],
    "education": "—",
    "certifications": [],
    "history": [],
    "notes": [],
    "vocaroo": "16YfGJtOircS",
    "intake": {
      "availability": "Full-time (40 hrs/week)",
      "experience": "Yes",
      "lateHours": "Yes",
      "device": "Intel(R) Core(TM) i5-8250U CPU 8 GB RAM 1.80GHz",
      "phoneModel": "iPhone 11",
      "internet": "41 Download Mbps, 18 Upload Mbps",
      "cvUrl": "https://drive.google.com/open?id=1F6_VNL26vJWkf4SKx6wPfd_f1zWCZADQ"
    }
  },
  "AD-3025": {
    "headline": "SDR applicant · prior sales experience",
    "pitch": "Applicant for the Sales Development Representative role. Real contact details, intro recording, and intake answers are captured from the application form below.",
    "location": "Addis Ababa, ET",
    "timezone": "EAT (UTC+3)",
    "hours": "Full-time (40 hrs/week)",
    "email": "solibaslu@gmail.com",
    "phone": "0924452546",
    "employer": "—",
    "contractType": "Full-time (40 hrs/week)",
    "payRate": "—",
    "billRate": "—",
    "margin": "—",
    "started": "—",
    "deployedSince": "—",
    "csat": null,
    "aht": null,
    "qa": 0,
    "tools": [],
    "education": "—",
    "certifications": [],
    "history": [],
    "notes": [],
    "vocaroo": "14eHTnivrHOL",
    "intake": {
      "availability": "Full-time (40 hrs/week)",
      "experience": "Yes",
      "lateHours": "Yes",
      "device": "Intel core i5 5th gen, 256 ssd, 8 gb ram",
      "phoneModel": "Iphone 12",
      "internet": "8 mb/s",
      "cvUrl": "https://drive.google.com/open?id=1cMQvUYW-qtokeGOUxHpSTyNN8ERFKOQm"
    }
  },
  "AD-3026": {
    "headline": "SDR applicant · prior sales experience",
    "pitch": "Applicant for the Sales Development Representative role. Real contact details, intro recording, and intake answers are captured from the application form below.",
    "location": "Addis Ababa, ET",
    "timezone": "EAT (UTC+3)",
    "hours": "Part-time (20–30 hrs/week)",
    "email": "maereg.hailu@icloud.com",
    "phone": "0921146390",
    "employer": "—",
    "contractType": "Part-time (20–30 hrs/week)",
    "payRate": "—",
    "billRate": "—",
    "margin": "—",
    "started": "—",
    "deployedSince": "—",
    "csat": null,
    "aht": null,
    "qa": 0,
    "tools": [],
    "education": "—",
    "certifications": [],
    "history": [],
    "notes": [],
    "vocaroo": "1leLC2juS3Rm",
    "intake": {
      "desiredSalary": "35,000 Birr",
      "availability": "Part-time (20–30 hrs/week)",
      "experience": "Yes",
      "lateHours": "Yes",
      "device": "16 GB RAM, Intel i5, 1 TB SSD",
      "phoneModel": "iPhone 14+",
      "internet": "25 Mbps",
      "cvUrl": "https://drive.google.com/open?id=1zYbXbliYHjf18aUJloEhvkO4a9IzSwzL"
    }
  },
  "AD-3027": {
    "headline": "SDR applicant · prior sales experience",
    "pitch": "Applicant for the Sales Development Representative role. Real contact details, intro recording, and intake answers are captured from the application form below.",
    "location": "Addis Ababa, ET",
    "timezone": "EAT (UTC+3)",
    "hours": "Full-time (40 hrs/week)",
    "email": "mulatumihret6@gmail.com",
    "phone": "+251983979260",
    "employer": "—",
    "contractType": "Full-time (40 hrs/week)",
    "payRate": "—",
    "billRate": "—",
    "margin": "—",
    "started": "—",
    "deployedSince": "—",
    "csat": null,
    "aht": null,
    "qa": 0,
    "tools": [],
    "education": "—",
    "certifications": [],
    "history": [],
    "notes": [],
    "vocaroo": "12hPbegNGX2f",
    "intake": {
      "desiredSalary": "40000.0",
      "availability": "Full-time (40 hrs/week)",
      "experience": "Yes",
      "lateHours": "Yes",
      "device": "16GB RAM ,intel i7, 512GB SSD",
      "phoneModel": "iphone 11",
      "internet": "30.0",
      "cvUrl": "https://drive.google.com/open?id=1vvSlu4QaRZBiScCrWL_gjHDYcmrx2jwJ"
    }
  },
  "AD-3028": {
    "headline": "SDR applicant · prior sales experience",
    "pitch": "Applicant for the Sales Development Representative role. Real contact details, intro recording, and intake answers are captured from the application form below.",
    "location": "Remote",
    "timezone": "—",
    "hours": "Flexible/Project-based",
    "email": "nanugirmau@gmail.com",
    "phone": "2.51989189411E11",
    "employer": "—",
    "contractType": "Flexible/Project-based",
    "payRate": "—",
    "billRate": "—",
    "margin": "—",
    "started": "—",
    "deployedSince": "—",
    "csat": null,
    "aht": null,
    "qa": 0,
    "tools": [],
    "education": "—",
    "certifications": [],
    "history": [],
    "notes": [],
    "vocaroo": "1mhGZasNs4cj",
    "intake": {
      "desiredSalary": "40000.0",
      "availability": "Flexible/Project-based",
      "experience": "Yes",
      "lateHours": "Yes",
      "device": "Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz   2.11 GHz",
      "phoneModel": "Samung S22",
      "internet": "50 Mbs",
      "cvUrl": "https://drive.google.com/open?id=1MDUeWTw1NRM7mo3mITJ9PGdY6xC8spN9"
    }
  },
  "AD-3029": {
    "headline": "SDR applicant · prior sales experience",
    "pitch": "Applicant for the Sales Development Representative role. Real contact details, intro recording, and intake answers are captured from the application form below.",
    "location": "Addis Ababa, ET",
    "timezone": "EAT (UTC+3)",
    "hours": "Flexible/Project-based",
    "email": "ruth.masresha.bekele@gmail.com",
    "phone": "+251904115682",
    "employer": "—",
    "contractType": "Flexible/Project-based",
    "payRate": "—",
    "billRate": "—",
    "margin": "—",
    "started": "—",
    "deployedSince": "—",
    "csat": null,
    "aht": null,
    "qa": 0,
    "tools": [],
    "education": "—",
    "certifications": [],
    "history": [],
    "notes": [],
    "vocaroo": "17RRW0tBEqt8",
    "intake": {
      "desiredSalary": "35000.0",
      "availability": "Flexible/Project-based",
      "experience": "Yes",
      "lateHours": "Yes",
      "device": "8 GB RAM, 12th Gen Intel(R) Core(TM)i5",
      "phoneModel": "Samsung S9",
      "internet": "10Mbps DL, 6 Mbps UL",
      "cvUrl": "https://drive.google.com/open?id=18zd6-ns8Wdger3orw7MCxVSNn_Ls45V_"
    }
  },
  "AD-3030": {
    "headline": "SDR applicant · prior sales experience",
    "pitch": "Applicant for the Sales Development Representative role. Real contact details, intro recording, and intake answers are captured from the application form below.",
    "location": "Addis Ababa, ET",
    "timezone": "EAT (UTC+3)",
    "hours": "Flexible/Project-based",
    "email": "redietdawit192@gmail.com",
    "phone": "+251920554343",
    "employer": "—",
    "contractType": "Flexible/Project-based",
    "payRate": "—",
    "billRate": "—",
    "margin": "—",
    "started": "—",
    "deployedSince": "—",
    "csat": null,
    "aht": null,
    "qa": 0,
    "tools": [],
    "education": "—",
    "certifications": [],
    "history": [],
    "notes": [],
    "vocaroo": "11Op3g3X3s9W",
    "intake": {
      "desiredSalary": "400 usd",
      "availability": "Flexible/Project-based",
      "experience": "Yes",
      "lateHours": "Yes",
      "device": "16GB Rams, i7, 512GB SSD",
      "phoneModel": "Samsung A15",
      "internet": "8M/S",
      "cvUrl": "https://drive.google.com/open?id=14Q5O9wjHyKf_5Zl2xUOX34kpKq7_Jjac"
    }
  },
  "AD-3031": {
    "headline": "SDR applicant · prior sales experience",
    "pitch": "Applicant for the Sales Development Representative role. Real contact details, intro recording, and intake answers are captured from the application form below.",
    "location": "Addis Ababa, ET",
    "timezone": "EAT (UTC+3)",
    "hours": "Flexible/Project-based",
    "email": "mahideredawit321@gmail.com",
    "phone": "+251936106964",
    "employer": "—",
    "contractType": "Flexible/Project-based",
    "payRate": "—",
    "billRate": "—",
    "margin": "—",
    "started": "—",
    "deployedSince": "—",
    "csat": null,
    "aht": null,
    "qa": 0,
    "tools": [],
    "education": "—",
    "certifications": [],
    "history": [],
    "notes": [],
    "vocaroo": "1g7yG9mtUwoJ",
    "intake": {
      "desiredSalary": "20,000 - 50,000",
      "availability": "Flexible/Project-based",
      "experience": "Yes",
      "lateHours": "Yes",
      "device": "RAM - 16GB, Intel i5",
      "phoneModel": "Iphone X",
      "internet": "20mbs",
      "cvUrl": "https://drive.google.com/open?id=1at6hswYmXp_xomu-w322T4q1_yK-Q1XK"
    }
  },
  "AD-3032": {
    "headline": "SDR applicant",
    "pitch": "Applicant for the Sales Development Representative role. Real contact details, intro recording, and intake answers are captured from the application form below.",
    "location": "Addis Ababa, ET",
    "timezone": "EAT (UTC+3)",
    "hours": "Part-time (20–30 hrs/week)",
    "email": "kidstshewangzaw13@gmail.com",
    "phone": "0922105737",
    "employer": "—",
    "contractType": "Part-time (20–30 hrs/week)",
    "payRate": "—",
    "billRate": "—",
    "margin": "—",
    "started": "—",
    "deployedSince": "—",
    "csat": null,
    "aht": null,
    "qa": 0,
    "tools": [],
    "education": "—",
    "certifications": [],
    "history": [],
    "notes": [],
    "vocaroo": "1hoHJwQqNPn0",
    "intake": {
      "desiredSalary": "30,000.00 ETB",
      "availability": "Part-time (20–30 hrs/week)",
      "experience": "No experience (but willing to learn)",
      "lateHours": "Yes",
      "device": "RAM 16.0G, 12TH GENERATION, STORAGE 512, INT i5",
      "phoneModel": "Android A23",
      "internet": "20mg/sec",
      "cvUrl": "https://drive.google.com/open?id=1VWZXqmNQYHmF5fS0MP8x_Uww_QzuFp_f"
    }
  },
  "AD-3033": {
    "headline": "SDR applicant · prior sales experience",
    "pitch": "Applicant for the Sales Development Representative role. Real contact details, intro recording, and intake answers are captured from the application form below.",
    "location": "Addis Ababa, ET",
    "timezone": "EAT (UTC+3)",
    "hours": "Full-time (40 hrs/week)",
    "email": "metsnanatt2@gmail.com",
    "phone": "+251946684780",
    "employer": "—",
    "contractType": "Full-time (40 hrs/week)",
    "payRate": "—",
    "billRate": "—",
    "margin": "—",
    "started": "—",
    "deployedSince": "—",
    "csat": null,
    "aht": null,
    "qa": 0,
    "tools": [],
    "education": "—",
    "certifications": [],
    "history": [],
    "notes": [],
    "vocaroo": "1c0zSUqaozQz",
    "intake": {
      "desiredSalary": "55,000-60,000",
      "availability": "Full-time (40 hrs/week)",
      "experience": "Yes",
      "lateHours": "Yes",
      "device": "16GB RAM, Intel core i5, 477GB",
      "phoneModel": "iPhone 14 promax",
      "internet": "40Mbps",
      "freelance": "yes, \nLinkedIn, Upwork, Glassdoor",
      "cvUrl": "https://drive.google.com/open?id=11hRVfV1isE5lgUWrcm5c9KuT0NkLA12A",
      "employed": "No"
    }
  },
  "AD-3034": {
    "headline": "SDR applicant · prior sales experience",
    "pitch": "Applicant for the Sales Development Representative role. Real contact details, intro recording, and intake answers are captured from the application form below.",
    "location": "Addis Ababa, ET",
    "timezone": "EAT (UTC+3)",
    "hours": "Part-time (20–30 hrs/week)",
    "email": "nebiat20000o@gmail.com",
    "phone": "+251980642124",
    "employer": "—",
    "contractType": "Part-time (20–30 hrs/week)",
    "payRate": "—",
    "billRate": "—",
    "margin": "—",
    "started": "—",
    "deployedSince": "—",
    "csat": null,
    "aht": null,
    "qa": 0,
    "tools": [],
    "education": "—",
    "certifications": [],
    "history": [],
    "notes": [],
    "vocaroo": "1m4ybfpyO4Wg",
    "intake": {
      "desiredSalary": "200-300",
      "availability": "Part-time (20–30 hrs/week)",
      "experience": "Yes",
      "lateHours": "Yes",
      "device": "Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (1.99 GHz)/8.00 GB (7.81 GB usable)/ 64-bit operating system, x64-based processor",
      "phoneModel": "android 12",
      "internet": "9-10 mps",
      "freelance": "yes, freelance",
      "cvUrl": "https://drive.google.com/open?id=1bNfFnziuE9oMLTUnbYkaFS2D58Rwo5LC",
      "employed": "No"
    }
  },
  "AD-3035": {
    "headline": "SDR applicant · prior sales experience",
    "pitch": "Applicant for the Sales Development Representative role. Real contact details, intro recording, and intake answers are captured from the application form below.",
    "location": "Remote",
    "timezone": "—",
    "hours": "Full-time (40 hrs/week)",
    "email": "natenegash379@gmail.com",
    "phone": "2.51928117525E11",
    "employer": "—",
    "contractType": "Full-time (40 hrs/week)",
    "payRate": "—",
    "billRate": "—",
    "margin": "—",
    "started": "—",
    "deployedSince": "—",
    "csat": null,
    "aht": null,
    "qa": 0,
    "tools": [],
    "education": "—",
    "certifications": [],
    "history": [],
    "notes": [],
    "vocaroo": "1kqBtxkeXWwt",
    "intake": {
      "desiredSalary": "50000.0",
      "availability": "Full-time (40 hrs/week)",
      "experience": "Yes",
      "lateHours": "Yes",
      "device": "core I5 512 gb ssd with 16gb ram",
      "phoneModel": "Samsung a15",
      "internet": "download speed 35 Mbps , upload speed 22 Mbps",
      "freelance": "Linkdin sales navigator",
      "cvUrl": "https://drive.google.com/open?id=1dJiBE-7vvjRRJsT1ZaXThIuBQjGc-BGE",
      "employed": "No"
    }
  },
  "AD-3036": {
    "headline": "SDR applicant · prior sales experience",
    "pitch": "Applicant for the Sales Development Representative role. Real contact details, intro recording, and intake answers are captured from the application form below.",
    "location": "Addis Ababa, ET",
    "timezone": "EAT (UTC+3)",
    "hours": "Part-time (20–30 hrs/week)",
    "email": "mullerherm51@gmail.com",
    "phone": "+251975081121",
    "employer": "—",
    "contractType": "Part-time (20–30 hrs/week)",
    "payRate": "—",
    "billRate": "—",
    "margin": "—",
    "started": "—",
    "deployedSince": "—",
    "csat": null,
    "aht": null,
    "qa": 0,
    "tools": [],
    "education": "—",
    "certifications": [],
    "history": [],
    "notes": [],
    "vocaroo": "19PsvB68pfx3",
    "intake": {
      "desiredSalary": "25,000-35000",
      "availability": "Part-time (20–30 hrs/week)",
      "experience": "Yes",
      "lateHours": "Yes",
      "device": "acer 4 gb ram, 218 ssd",
      "phoneModel": "Samsung note 20, andriod 12",
      "internet": "20 mbps downlaod 12 mbps upload.",
      "freelance": "www.linkedin.com/in/hermella-mulugeta-202292242",
      "cvUrl": "https://drive.google.com/open?id=1wnoFnA4Im4XQ9scKv8Em9Zqk2bnmccJm",
      "employed": "No"
    }
  },
  "AD-3037": {
    "headline": "SDR applicant · prior sales experience",
    "pitch": "Applicant for the Sales Development Representative role. Real contact details, intro recording, and intake answers are captured from the application form below.",
    "location": "Addis Ababa, ET",
    "timezone": "EAT (UTC+3)",
    "hours": "Full-time (40 hrs/week)",
    "email": "abenefek@gmail.com",
    "phone": "+251922826661",
    "employer": "—",
    "contractType": "Full-time (40 hrs/week)",
    "payRate": "—",
    "billRate": "—",
    "margin": "—",
    "started": "—",
    "deployedSince": "—",
    "csat": null,
    "aht": null,
    "qa": 0,
    "tools": [],
    "education": "—",
    "certifications": [],
    "history": [],
    "notes": [],
    "vocaroo": "1akTk82OMhuL",
    "intake": {
      "desiredSalary": "80,000- 90,000 Full time",
      "availability": "Full-time (40 hrs/week)",
      "experience": "Yes",
      "lateHours": "Yes",
      "device": "8GB",
      "phoneModel": "IPHONE SE 2020 5G",
      "internet": "35Mb/sec",
      "freelance": "LinkedIn",
      "cvUrl": "https://drive.google.com/open?id=1hYpKPR36Nd0VYOCVN_5O9ivNWOQcRyjO",
      "employed": "Yes, part-time"
    }
  },
  "AD-3038": {
    "headline": "SDR applicant",
    "pitch": "Applicant for the Sales Development Representative role. Real contact details, intro recording, and intake answers are captured from the application form below.",
    "location": "Addis Ababa, ET",
    "timezone": "EAT (UTC+3)",
    "hours": "Flexible/Project-based",
    "email": "tgkifle92@gmail.com",
    "phone": "0991722123",
    "employer": "—",
    "contractType": "Flexible/Project-based",
    "payRate": "—",
    "billRate": "—",
    "margin": "—",
    "started": "—",
    "deployedSince": "—",
    "csat": null,
    "aht": null,
    "qa": 0,
    "tools": [],
    "education": "—",
    "certifications": [],
    "history": [],
    "notes": [],
    "vocaroo": "1j2tjx9E8ZqE",
    "intake": {
      "desiredSalary": "30000.0",
      "availability": "Flexible/Project-based",
      "experience": "No experience (but willing to learn)",
      "lateHours": "Yes",
      "device": "16GB RAM ,i7 PROCESSER ,510GB",
      "phoneModel": "Android 13",
      "internet": "25 MBS",
      "freelance": "NO",
      "cvUrl": "https://drive.google.com/open?id=111BYqHMC9moCRpfjitRVMaCd6LCO-szh",
      "employed": "No"
    }
  },
  "AD-3039": {
    "headline": "SDR applicant · prior sales experience",
    "pitch": "Applicant for the Sales Development Representative role. Real contact details, intro recording, and intake answers are captured from the application form below.",
    "location": "Addis Ababa, ET",
    "timezone": "EAT (UTC+3)",
    "hours": "Full-time (40 hrs/week)",
    "email": "ermiasabadiaynalem@gmail.com",
    "phone": "+251911463440",
    "employer": "—",
    "contractType": "Full-time (40 hrs/week)",
    "payRate": "—",
    "billRate": "—",
    "margin": "—",
    "started": "—",
    "deployedSince": "—",
    "csat": null,
    "aht": null,
    "qa": 0,
    "tools": [],
    "education": "—",
    "certifications": [],
    "history": [],
    "notes": [],
    "vocaroo": "18cZDvlL2LjT",
    "intake": {
      "desiredSalary": "50000.0",
      "availability": "Full-time (40 hrs/week)",
      "experience": "Yes",
      "lateHours": "Yes",
      "device": "8GB, Intel i5, 512 GB SSD",
      "phoneModel": "iphone 12",
      "internet": "40.0",
      "freelance": "upwork",
      "cvUrl": "https://drive.google.com/open?id=1Ak9eK1TuMS4Rs0pEyZ4FgxwVR40aJ3A9",
      "employed": "Yes, part-time"
    }
  },
  "AD-3040": {
    "headline": "SDR applicant · prior sales experience",
    "pitch": "Applicant for the Sales Development Representative role. Real contact details, intro recording, and intake answers are captured from the application form below.",
    "location": "Addis Ababa, ET",
    "timezone": "EAT (UTC+3)",
    "hours": "Full-time (40 hrs/week)",
    "email": "amanuelbelete64@gmail.com",
    "phone": "+251944242766",
    "employer": "—",
    "contractType": "Full-time (40 hrs/week)",
    "payRate": "—",
    "billRate": "—",
    "margin": "—",
    "started": "—",
    "deployedSince": "—",
    "csat": null,
    "aht": null,
    "qa": 0,
    "tools": [],
    "education": "—",
    "certifications": [],
    "history": [],
    "notes": [],
    "vocaroo": "1dv2M6ogNBex",
    "intake": {
      "desiredSalary": "60,000-80,000",
      "availability": "Full-time (40 hrs/week)",
      "experience": "Yes",
      "lateHours": "Yes",
      "device": "8GB RAM, GTX 1650 TI i5, 512GB SSD",
      "phoneModel": "iPhone 11 pro",
      "internet": "20 mbps up and 22 mbps down",
      "freelance": "No",
      "cvUrl": "https://drive.google.com/open?id=1nE5DNG7AhEf17kThqEEr4AWI7uxUfC08",
      "employed": "No"
    }
  },
  "AD-3041": {
    "headline": "SDR applicant · prior sales experience",
    "pitch": "Applicant for the Sales Development Representative role. Real contact details, intro recording, and intake answers are captured from the application form below.",
    "location": "Addis Ababa, ET",
    "timezone": "EAT (UTC+3)",
    "hours": "Full-time (40 hrs/week)",
    "email": "rachelteshome16@gmail.com",
    "phone": "0922582259",
    "employer": "—",
    "contractType": "Full-time (40 hrs/week)",
    "payRate": "—",
    "billRate": "—",
    "margin": "—",
    "started": "—",
    "deployedSince": "—",
    "csat": null,
    "aht": null,
    "qa": 0,
    "tools": [],
    "education": "—",
    "certifications": [],
    "history": [],
    "notes": [],
    "vocaroo": "1cFXLQzf5ro0",
    "intake": {
      "desiredSalary": "40000-50000birr",
      "availability": "Full-time (40 hrs/week)",
      "experience": "Yes",
      "lateHours": "Yes",
      "device": "4GB ,120RAM Intel(R) core(TM) i5-7200u CPU 2.50@",
      "phoneModel": "Samsung Galaxy A13",
      "internet": "Download -93.65Mbs    upload-94.",
      "freelance": "No",
      "cvUrl": "https://drive.google.com/open?id=1f4CfX6bTH65QR09iZv2pVISau9CTuOct",
      "employed": "Yes, part-time"
    }
  },
  "AD-3042": {
    "headline": "SDR applicant · prior sales experience",
    "pitch": "Applicant for the Sales Development Representative role. Real contact details, intro recording, and intake answers are captured from the application form below.",
    "location": "Addis Ababa, ET",
    "timezone": "EAT (UTC+3)",
    "hours": "Full-time (40 hrs/week)",
    "email": "mahitsige11@gmail.com",
    "phone": "+251941139423",
    "employer": "—",
    "contractType": "Full-time (40 hrs/week)",
    "payRate": "—",
    "billRate": "—",
    "margin": "—",
    "started": "—",
    "deployedSince": "—",
    "csat": null,
    "aht": null,
    "qa": 0,
    "tools": [],
    "education": "—",
    "certifications": [],
    "history": [],
    "notes": [],
    "vocaroo": "17uqEVzXFuqV",
    "intake": {
      "desiredSalary": "60000-80000",
      "availability": "Full-time (40 hrs/week)",
      "experience": "Yes",
      "lateHours": "Yes",
      "device": "My laptop has 8GB RAM , an intel i5 processor and 512GB SSD.",
      "phoneModel": "Android 12",
      "internet": "30Mbps",
      "freelance": "No",
      "cvUrl": "https://drive.google.com/open?id=1mGldY2QUcsHQ7HnhWqEbBYYRspfFhE9Q",
      "employed": "Yes, full-time"
    }
  },
  "AD-3043": {
    "headline": "SDR applicant · prior sales experience",
    "pitch": "Applicant for the Sales Development Representative role. Real contact details, intro recording, and intake answers are captured from the application form below.",
    "location": "Addis Ababa, ET",
    "timezone": "EAT (UTC+3)",
    "hours": "Full-time (40 hrs/week)",
    "email": "Kunuzmoha@gmail.com",
    "phone": "0965041846",
    "employer": "—",
    "contractType": "Full-time (40 hrs/week)",
    "payRate": "—",
    "billRate": "—",
    "margin": "—",
    "started": "—",
    "deployedSince": "—",
    "csat": null,
    "aht": null,
    "qa": 0,
    "tools": [],
    "education": "—",
    "certifications": [],
    "history": [],
    "notes": [],
    "vocaroo": "12oTzwQ1V1d3",
    "intake": {
      "desiredSalary": "65,000-85,000",
      "availability": "Full-time (40 hrs/week)",
      "experience": "Yes",
      "lateHours": "Yes",
      "device": "16GB RAM, 512GB SSD, intel i7, 12th generation",
      "phoneModel": "iPhone 12pro, iOS 26",
      "internet": "40mbps download , 20-30mbps upload",
      "freelance": "No I have not",
      "cvUrl": "https://drive.google.com/open?id=1bdtH_7B_PGTjwrw2JCNg1kHUURGZBLLp",
      "employed": "No"
    }
  },
  "AD-3044": {
    "headline": "SDR applicant",
    "pitch": "Applicant for the Sales Development Representative role. Real contact details, intro recording, and intake answers are captured from the application form below.",
    "location": "Addis Ababa, ET",
    "timezone": "EAT (UTC+3)",
    "hours": "Full-time (40 hrs/week)",
    "email": "abelaeleni@gmail.com",
    "phone": "0990047424",
    "employer": "—",
    "contractType": "Full-time (40 hrs/week)",
    "payRate": "—",
    "billRate": "—",
    "margin": "—",
    "started": "—",
    "deployedSince": "—",
    "csat": null,
    "aht": null,
    "qa": 0,
    "tools": [],
    "education": "—",
    "certifications": [],
    "history": [],
    "notes": [],
    "vocaroo": "1hvPCxx1eOE8",
    "intake": {
      "desiredSalary": "60000_80000",
      "availability": "Full-time (40 hrs/week)",
      "experience": "No experience (but willing to learn)",
      "lateHours": "Yes",
      "device": "Cori 5 , 8 gb ram, 1tb",
      "phoneModel": "ZTE blade",
      "internet": "5mps",
      "freelance": "No",
      "cvUrl": "https://drive.google.com/open?id=19z3cXq7M9MogzvCzpDTrDgfuuXvc9KJ1",
      "employed": "No"
    }
  },
  "AD-3045": {
    "headline": "SDR applicant · prior sales experience",
    "pitch": "Applicant for the Sales Development Representative role. Real contact details, intro recording, and intake answers are captured from the application form below.",
    "location": "Addis Ababa, ET",
    "timezone": "EAT (UTC+3)",
    "hours": "Full-time (40 hrs/week)",
    "email": "abiruk12@gmail.com",
    "phone": "+251912803473",
    "employer": "—",
    "contractType": "Full-time (40 hrs/week)",
    "payRate": "—",
    "billRate": "—",
    "margin": "—",
    "started": "—",
    "deployedSince": "—",
    "csat": null,
    "aht": null,
    "qa": 0,
    "tools": [],
    "education": "—",
    "certifications": [],
    "history": [],
    "notes": [],
    "introUrl": "https://www.loom.com/share/0ee7f97da6fe49b193cdb825c8e567be",
    "intake": {
      "desiredSalary": "Around 40000 Birr",
      "availability": "Full-time (40 hrs/week)",
      "experience": "Yes",
      "lateHours": "Yes",
      "device": "Storage: 256 SSD , 2TB HDD RAM: 16 GB , Processor: Intel Core i7 , GPU: GTX 1060 6GB",
      "phoneModel": "ROG Phone 7 , Android 15",
      "internet": "30Mbps",
      "freelance": "Yes LinkedIn mainly but also Fiverr too",
      "cvUrl": "https://drive.google.com/open?id=1bNMOO8u5riB80ywPiQFGO6PFMGnW_n2T",
      "employed": "Yes, part-time"
    }
  },
  "AD-3046": {
    "headline": "SDR applicant · prior sales experience",
    "pitch": "Applicant for the Sales Development Representative role. Real contact details, intro recording, and intake answers are captured from the application form below.",
    "location": "Addis Ababa, ET",
    "timezone": "EAT (UTC+3)",
    "hours": "Full-time (40 hrs/week)",
    "email": "ezanah007@gmail.com",
    "phone": "0929176234",
    "employer": "—",
    "contractType": "Full-time (40 hrs/week)",
    "payRate": "—",
    "billRate": "—",
    "margin": "—",
    "started": "—",
    "deployedSince": "—",
    "csat": null,
    "aht": null,
    "qa": 0,
    "tools": [],
    "education": "—",
    "certifications": [],
    "history": [],
    "notes": [],
    "vocaroo": "1bIqBL9jUNLQ",
    "intake": {
      "desiredSalary": "30,000-60,000",
      "availability": "Full-time (40 hrs/week)",
      "experience": "Yes",
      "lateHours": "Yes",
      "device": "16GB RAM, AMD Ryzen 5 PRO, 512GB SSD",
      "phoneModel": "samsung 8+",
      "internet": "5.26 Mbps",
      "freelance": "upwork, reddit and fiverr",
      "cvUrl": "https://drive.google.com/open?id=14uL_B9YiCyQvRKlKaQSOKQOVlvAU6Bqh",
      "employed": "Yes, part-time"
    }
  },
  "AD-3047": {
    "headline": "SDR applicant",
    "pitch": "Applicant for the Sales Development Representative role. Real contact details, intro recording, and intake answers are captured from the application form below.",
    "location": "Addis Ababa, ET",
    "timezone": "EAT (UTC+3)",
    "hours": "Full-time (40 hrs/week)",
    "email": "amanranzel@gmail.com",
    "phone": "0996606318",
    "employer": "—",
    "contractType": "Full-time (40 hrs/week)",
    "payRate": "—",
    "billRate": "—",
    "margin": "—",
    "started": "—",
    "deployedSince": "—",
    "csat": null,
    "aht": null,
    "qa": 0,
    "tools": [],
    "education": "—",
    "certifications": [],
    "history": [],
    "notes": [],
    "vocaroo": "14bMhRB9EMnF",
    "intake": {
      "desiredSalary": "25000-50000",
      "availability": "Full-time (40 hrs/week)",
      "experience": "No experience (but willing to learn)",
      "lateHours": "Yes",
      "device": "16Gb RAM,Intel i5, 512GB",
      "phoneModel": "Android 14",
      "internet": "20mbs",
      "freelance": "LinkedIn",
      "cvUrl": "https://drive.google.com/open?id=1w2mdjnWoYvZzX840r9Imt0_ojEbPY2sV",
      "employed": "No"
    }
  },
  "AD-3048": {
    "headline": "SDR applicant",
    "pitch": "Applicant for the Sales Development Representative role. Real contact details, intro recording, and intake answers are captured from the application form below.",
    "location": "Addis Ababa, ET",
    "timezone": "EAT (UTC+3)",
    "hours": "Part-time (20–30 hrs/week)",
    "email": "hermela.asf23@gmail.com",
    "phone": "+251911408123",
    "employer": "—",
    "contractType": "Part-time (20–30 hrs/week)",
    "payRate": "—",
    "billRate": "—",
    "margin": "—",
    "started": "—",
    "deployedSince": "—",
    "csat": null,
    "aht": null,
    "qa": 0,
    "tools": [],
    "education": "—",
    "certifications": [],
    "history": [],
    "notes": [],
    "vocaroo": "1oHdHFHbEo68",
    "intake": {
      "desiredSalary": "80,000 birr",
      "availability": "Part-time (20–30 hrs/week)",
      "experience": "No experience (but willing to learn)",
      "lateHours": "No",
      "device": "8GB RAM, Intel(R)Core(TM) i5-6200U CPU @2.30GHz",
      "phoneModel": "Iphone 13 Pro",
      "internet": "20.0",
      "freelance": "I have not",
      "cvUrl": "https://drive.google.com/open?id=1sAFxKNpA-iVq0s30IqcWxc-Jvyq9AAGy",
      "employed": "Yes, full-time"
    }
  },
  "AD-3049": {
    "headline": "SDR applicant · prior sales experience",
    "pitch": "Applicant for the Sales Development Representative role. Real contact details, intro recording, and intake answers are captured from the application form below.",
    "location": "Addis Ababa, ET",
    "timezone": "EAT (UTC+3)",
    "hours": "Flexible/Project-based",
    "email": "selamzecom@gmail.com",
    "phone": "0996893011",
    "employer": "—",
    "contractType": "Flexible/Project-based",
    "payRate": "—",
    "billRate": "—",
    "margin": "—",
    "started": "—",
    "deployedSince": "—",
    "csat": null,
    "aht": null,
    "qa": 0,
    "tools": [],
    "education": "—",
    "certifications": [],
    "history": [],
    "notes": [],
    "vocaroo": "19laC2RYjvmT",
    "intake": {
      "desiredSalary": "based on the company scale",
      "availability": "Flexible/Project-based",
      "experience": "Yes",
      "lateHours": "Yes",
      "device": "16GB RAM, Intel i7, 512GB SSD",
      "phoneModel": "Iphone11",
      "internet": "94.14 Mbps",
      "freelance": "No",
      "cvUrl": "https://drive.google.com/open?id=1gl7xWT8WIWBllMAWdZYIm-xcZFuOF80-",
      "employed": "Yes, full-time"
    }
  },
  "AD-3050": {
    "headline": "SDR applicant · prior sales experience",
    "pitch": "Applicant for the Sales Development Representative role. Real contact details, intro recording, and intake answers are captured from the application form below.",
    "location": "Addis Ababa, ET",
    "timezone": "EAT (UTC+3)",
    "hours": "Full-time (40 hrs/week)",
    "email": "eteacher773@gmail.com",
    "phone": "+251900030780",
    "employer": "—",
    "contractType": "Full-time (40 hrs/week)",
    "payRate": "—",
    "billRate": "—",
    "margin": "—",
    "started": "—",
    "deployedSince": "—",
    "csat": null,
    "aht": null,
    "qa": 0,
    "tools": [],
    "education": "—",
    "certifications": [],
    "history": [],
    "notes": [],
    "vocaroo": "15xLK6BgtQ3e",
    "intake": {
      "desiredSalary": "70,000-90,000 Birr",
      "availability": "Full-time (40 hrs/week)",
      "experience": "Yes",
      "lateHours": "Yes",
      "device": "8GB RAM Intel(R) Celeron(R) N4100 CPU @ 1.10GHz (1.10 GHz)",
      "phoneModel": "iphone 15",
      "internet": "9.12-10.98 Mbdps",
      "freelance": "I have worked Upwork",
      "cvUrl": "https://drive.google.com/open?id=1P78AFR6nEHRJIcahezHRMlJ3JK1QvEeH",
      "employed": "Yes, full-time"
    }
  },
  "AD-3051": {
    "headline": "SDR applicant · prior sales experience",
    "pitch": "Applicant for the Sales Development Representative role. Real contact details, intro recording, and intake answers are captured from the application form below.",
    "location": "Addis Ababa, ET",
    "timezone": "EAT (UTC+3)",
    "hours": "Full-time (40 hrs/week)",
    "email": "gigiteshomelila@gmail.com",
    "phone": "+251955927117",
    "employer": "—",
    "contractType": "Full-time (40 hrs/week)",
    "payRate": "—",
    "billRate": "—",
    "margin": "—",
    "started": "—",
    "deployedSince": "—",
    "csat": null,
    "aht": null,
    "qa": 0,
    "tools": [],
    "education": "—",
    "certifications": [],
    "history": [],
    "notes": [],
    "vocaroo": "1ayGg4A7EloS",
    "intake": {
      "desiredSalary": "78000-82000 ETB",
      "availability": "Full-time (40 hrs/week)",
      "experience": "Yes",
      "lateHours": "Yes",
      "device": "System Unit: Laptop, 11th Gen Intel® Core™ i7-1185G7 @ 3.00 GHZ, 16 GB RAM, 256 GB SSD, 64-bit system (x64-based) Operating System: Windows 11 Pro, Version 25H2 (64-bit)",
      "phoneModel": "iPhone 16 plus",
      "internet": "200mbps",
      "freelance": "no",
      "cvUrl": "https://drive.google.com/open?id=102d--OlybQ63on-7LENtJ4FlWYuzDuCC",
      "employed": "No"
    }
  },
  "AD-3052": {
    "headline": "SDR applicant · prior sales experience",
    "pitch": "Applicant for the Sales Development Representative role. Real contact details, intro recording, and intake answers are captured from the application form below.",
    "location": "Addis Ababa, ET",
    "timezone": "EAT (UTC+3)",
    "hours": "Full-time (40 hrs/week)",
    "email": "helinatteshale@gmail.com",
    "phone": "0922474040",
    "employer": "—",
    "contractType": "Full-time (40 hrs/week)",
    "payRate": "—",
    "billRate": "—",
    "margin": "—",
    "started": "—",
    "deployedSince": "—",
    "csat": null,
    "aht": null,
    "qa": 0,
    "tools": [],
    "education": "—",
    "certifications": [],
    "history": [],
    "notes": [],
    "vocaroo": "12X6rIiOD0d1",
    "intake": {
      "desiredSalary": "70-80k",
      "availability": "Full-time (40 hrs/week)",
      "experience": "Yes",
      "lateHours": "Yes",
      "device": "16GB RAM, Intel i5, 512GB SSD",
      "phoneModel": "iPhone 13 pro",
      "internet": "50 download mbps, 40 upload mbps",
      "freelance": "No",
      "cvUrl": "https://drive.google.com/open?id=1HLjszaxoWClUU-ysFCyCuXddS2aoWnAB",
      "employed": "No"
    }
  },
  "AD-3053": {
    "headline": "SDR applicant",
    "pitch": "Applicant for the Sales Development Representative role. Real contact details, intro recording, and intake answers are captured from the application form below.",
    "location": "Remote",
    "timezone": "—",
    "hours": "Full-time (40 hrs/week)",
    "email": "samrawit.yeshitila2@gmail.com",
    "phone": "2.51941428324E11",
    "employer": "—",
    "contractType": "Full-time (40 hrs/week)",
    "payRate": "—",
    "billRate": "—",
    "margin": "—",
    "started": "—",
    "deployedSince": "—",
    "csat": null,
    "aht": null,
    "qa": 0,
    "tools": [],
    "education": "—",
    "certifications": [],
    "history": [],
    "notes": [],
    "vocaroo": "14x4l2hNmYoX",
    "intake": {
      "desiredSalary": "Negotiable",
      "availability": "Full-time (40 hrs/week)",
      "experience": "No experience (but willing to learn)",
      "lateHours": "Yes",
      "device": ".8GB RAM, Intel Core i7-1355U, 256GB SSD",
      "phoneModel": "iPhone 12",
      "internet": "10 Mbps Download / 10 Mbps Upload",
      "freelance": "I have not yet worked on freelance platforms like Upwork or Fiverr, but I understand they are essential for connecting with global clients. My Economics training involved extensive online research, data gathering, and analysisskills that directly apply to identifying and researching potential leads as an SDR. I am a fast learner and am confident I can quickly adapt to using these platforms effectively to support client outreach and engagement.",
      "cvUrl": "https://drive.google.com/open?id=1iVEaK6EQOUZyc1ZUEum6JIvOJcWNQl_o",
      "employed": "No"
    }
  },
  "AD-3054": {
    "headline": "SDR applicant",
    "pitch": "Applicant for the Sales Development Representative role. Real contact details, intro recording, and intake answers are captured from the application form below.",
    "location": "Addis Ababa, ET",
    "timezone": "EAT (UTC+3)",
    "hours": "Full-time (40 hrs/week)",
    "email": "redwanibrahim19@gmail.com",
    "phone": "0978800596",
    "employer": "—",
    "contractType": "Full-time (40 hrs/week)",
    "payRate": "—",
    "billRate": "—",
    "margin": "—",
    "started": "—",
    "deployedSince": "—",
    "csat": null,
    "aht": null,
    "qa": 0,
    "tools": [],
    "education": "—",
    "certifications": [],
    "history": [],
    "notes": [],
    "introUrl": "https://drive.google.com/file/d/1vK5JZaxXrimouMUkOCWYUGTFzlAtqJjw/view?usp=sharing",
    "intake": {
      "desiredSalary": "40,000 birr",
      "availability": "Full-time (40 hrs/week)",
      "experience": "No experience (but willing to learn)",
      "lateHours": "Yes",
      "device": "8GB RAM, Intel i3, 233GB",
      "phoneModel": "Samsung Galaxy A14, Android 15",
      "internet": "Download Mbps: 19.12, Upload Mbps: 10.73",
      "freelance": "No, i haven't worked on this platforms before.",
      "cvUrl": "https://drive.google.com/open?id=1czr9qM1Pg0jhVrDUSfZrPV3C2vKd0sEK",
      "employed": "No"
    }
  }
}
